### ISSUE TITLE
[BUG] Empty string being returned

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#59]
### What bug did you encounter?

Upon accessing API routes in the browser, the list of articles includes some empty strings

### What did you expect to happen?

If an article is empty, it should not be included in the list

### Screenshots

`""` returned from BBC news source:
![image](https://user-images.githubusercontent.com/90829439/170477835-2db94792-8413-48b6-88b6-5b85f919f9f2.png)

### Additional information

The problem lies in `src/utils/getDataFromCheerio.js` where two variables `filterTitle` & `url` that are declared as empty string before being filled.
```js
function getDataFromCheerio(html) {
  if (!html) throw new Error('There is nothing to load here');

  let filterTitle = '';
  let url = '';

  const $ = cheerio.load(html);
...
```

removing these and just allowing the variable to be set **if** there is any data to set them with further down inside this method will prevent this problem.

**Comment by dcordoba97** [comment]
Hello team!

### Task
By removing the value from `filterTitle` & `url` I tripped on a similar bug.
![image](https://user-images.githubusercontent.com/46203203/170560052-aa35d1c6-6501-4d2d-af08-31811c23a0a0.png)

**Comment by dcordoba97** [comment]
Hey team!

## Task
- If an article is empty, it should not be included in the list

As told before, I removed the value from `filterTitle` & `url` and found a similar bug:

![image](https://user-images.githubusercontent.com/46203203/170560223-365995d5-8a43-4806-a90d-7265d17cb51d.png)

## Idea / Proposal

- First thing that came to my mind while reading the issue was to evaluate the value from title right before printing it. So I gave it a try: `src/controller/api/newsAPIController.js`

![image](https://user-images.githubusercontent.com/46203203/170560477-88603566-f746-494a-923f-ffbecabb32a8.png)

It is a pleasure to continue contributing to this project! Please let me know if you have any questions.

**Comment by MizouziE** [comment]
@dcordoba97 Hey man, thanks for looking into this. It's strange though as I am not getting any undefined values being returned. 
## For example this is with the code as it is now:
![image](https://user-images.githubusercontent.com/90829439/170572440-63e81297-0fca-4745-8d4e-5a85ab30f90b.png)

## And then by just commenting out lines 7 & 8 in`getDataFromCheerio.js` I get this response:
![image](https://user-images.githubusercontent.com/90829439/170572644-f8bd94f7-9596-4f1c-842f-f09e414ee1a6.png)

I am not against the sanity check in the controller, I'm just surprised that it is possible to get such varied results. I'd be interested to know what anybody else gets back from just removing lines 7 & 8?

**Comment by MizouziE** [comment]
# Hold the phone!
I am wrong! My method introduces a *new* bug that messes with the order of things being passed back to the controller on closer inspection.

@dcordoba97 please go with your way as it is avoiding the issue my way causes. I have mentioned another problem in #60 that I believe may be related and once THAT is solved it would put this to bed, but your way still comes out on top at this moment in time.

Thanks a lot for finding this! 🔎
